# .woodpecker.yml

when:
  event: [push, manual]
  branch: main

steps:
  build:
    image: node:22-alpine
    environment:
      CI_REPO_TRUSTED_VOLUMES=true
    commands:
      - npm ci
      - VITE_BASE_PATH=frontend/$CI_REPO_OWNER npm run build

  deploy:
    image: alpine
    environment:
      CI_REPO_TRUSTED_VOLUMES=true
    commands:
      - mkdir -p /mnt/pages
      - mount --bind /var/www/pages /mnt/pages
      - mkdir -p /mnt/pages/frontend/$CI_REPO_OWNER
      - rm -rf /mnt/pages/frontend/$CI_REPO_OWNER/*
      - cp -r dist/. /mnt/pages/frontend/$CI_REPO_OWNER/
      - umount /mnt/pages
