# .woodpecker.yml

when:
  event: [push, manual]
  branch: main

steps:
  build:
    image: node:22-alpine
    commands:
      - npm ci
      - VITE_BASE_PATH=frontend/$CI_REPO_OWNER npm run build

  deploy:
    image: alpine
    volumes:
      - /opt/dest_html:/var/www/pages
    commands:
      # CI_REPO_OWNER = a tanuló GitHub felhasználóneve
      - mkdir -p /var/www/pages/$CI_REPO_OWNER
      - rm -rf /var/www/pages/$CI_REPO_OWNER/*
      - cp -r dist/. /var/www/pages/$CI_REPO_OWNER/
